routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'admin'], function () {

    Route::get('/', function () {
        return view('admin.index');
    });

    Route::resource('/topic', 'control\TopicController');
    Route::resource('/post', 'control\PostController');

});

app/Http/Controllers/TopicController.php
<?php

namespace App\Http\Controllers;

use App\Http\Resources\Topic\TopicResource;
use App\Model\Topic;
use Illuminate\Http\Request;

class TopicController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return Topic::all();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function show(Topic $topic)
    {
        //
        return new TopicResource($topic);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function edit(Topic $topic)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Topic $topic)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function destroy(Topic $topic)
    {
        //
    }
}

app/Http/Controllers/control/TopicController.php
<?php

namespace App\Http\Controllers\control;

use App\Http\Controllers\Controller;
use App\Model\Topic;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class TopicController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $topics = Topic::orderBy('id','desc')->paginate(10);
        return view('admin.topic.index',['topics'=>$topics]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.topic.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'name'=>'required',
            'image'=>'mimes:png,jpg'
        ],[
            'name.require'=>"please enter name"
        ]);

        $fileName = 'default.jpg';
        if ($request->image) {
            try {
                $fileName = 'topic-'.time().'.'.$request->image->extension();
                $request->image->move(public_path('uploads'), $fileName);
            } catch (\Throwable $th) {
                throw $th;
            }

        }





        $topic = new Topic();
        $topic->name = $request->name;
        $topic->slug = Str::slug($request->name,'-');
        $topic->image = $fileName;
        $topic->save();

        return redirect()->back()->with('success','Created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $topic = Topic::find($id)->first();
        return view('admin.topic.edit',['topic'=>$topic]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $request->validate([
            'name'=>'required',
            'image'=>'mimes:png,jpg'
        ],[
            'name.require'=>"please enter name"
        ]);

        $fileName = 'default.jpg';
        if ($request->image) {
            try {
                $fileName = 'topic-'.time().'.'.$request->image->extension();
                $request->image->move(public_path('uploads'), $fileName);
            } catch (\Throwable $th) {
                throw $th;
            }

        }





        $topic = Topic::find($id)->first();
        $topic->name = $request->name;
        $topic->slug = Str::slug($request->name,'-');
        if($request->image){
            $topic->image = $fileName;
        }
        $topic->update();

        return redirect()->back()->with('success','Updated successfully');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        try {
            //code...
            Topic::find($id)->delete();
        } catch (Exception $er) {
            return redirect()->back()->with('failed','Delete Failed');
        }

       return redirect()->back()->with('success','Delete Successfull');
    }
}

resources/views/admin/topic/create.blade.php
@extends('admin.layouts.master')

@section('content')

    <div class="row">
        <div>
            @if(session()->has('success'))
            <div class="alert alert-success" >
                {{ session()->get('success') }}
            </div>
            @endif
            @if(session()->has('failed'))
            <div class="alert alert-success" >
                {{ session()->get('failed') }}
            </div>
            @endif
        </div>


        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                  <h3 class="card-title">Quick Example</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form role="form" action="{{route('topic.store')}}" method="POST" enctype="multipart/form-data" >
                  @csrf
                    <div class="card-body">
                    <div class="form-group">
                      <label for="topicName">Name</label>
                      <input name="name" type="text" class="form-control" id="topicName" placeholder="Enter Topic Name">
                    </div>

                    <div class="form-group">
                      <label for="exampleInputFile">File input</label>
                      <div class="input-group">
                        <div class="custom-file">
                          <input name="image" type="file" class="custom-file-input" id="file">
                          <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                        </div>
                        <div class="input-group-append">
                          <span class="input-group-text" id="">Upload</span>
                        </div>
                      </div>
                    </div>
                    <div id="uploadForm">
                        {{-- file preview here --}}
                    </div>
                  </div>
                  <!-- /.card-body -->

                  <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </div>
                </form>
              </div>
        </div>
    </div>
@endsection

resources/views/admin/topic/edit.blade.php
@extends('admin.layouts.master')

@section('content')

    <div class="row">
        <div>
            @if(session()->has('success'))
            <div class="alert alert-success" >
                {{ session()->get('success') }}
            </div>
            @endif
            @if(session()->has('failed'))
            <div class="alert alert-success" >
                {{ session()->get('failed') }}
            </div>
            @endif
        </div>


        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                  <h3 class="card-title">Quick Example</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form role="form" action="{{route('topic.update',$topic->id)}}" method="POST" enctype="multipart/form-data" >
                  @csrf
                  @method('PUT')
                    <div class="card-body">
                    <div class="form-group">
                      <label for="topicName">Name</label>
                      <input value="{{$topic->name}}" name="name" type="text" class="form-control" id="topicName" placeholder="Enter Topic Name">
                    </div>

                    <div class="form-group">
                      <label for="exampleInputFile">File input</label>
                      <div class="input-group"  id="uploadForm">
                        <div class="custom-file">
                          <input name="image" type="file" class="custom-file-input" id="file">
                          <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                        </div>
                        <div class="input-group-append" >
                          <span class="input-group-text" id="">Upload</span>
                        </div>
                      </div>
                      <img src="{{ filter_var($topic->image, FILTER_VALIDATE_URL)?$topic->image:asset('uploads/'.$topic->image) }}" alt="" width="100" height="100">

                    </div>

                  </div>
                  <!-- /.card-body -->

                  <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </div>
                </form>
              </div>
        </div>
    </div>
@endsection

resources/views/admin/topic/index.blade.php
@extends('admin.layouts.master')

@section('content')
<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Responsive Hover Table</h3>

          <div class="card-tools">
            <a href="{{route('topic.create')}}" class="btn btn-success" style="margin-left:100">Add New</a>

            <div class="input-group input-group-sm" style="width: 150px;">

              <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

              <div class="input-group-append">
                <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
              </div>
            </div>
          </div>
        </div>
        <div>
            @if(session()->has('success'))
            <div class="alert alert-success" >
                {{ session()->get('success') }}
            </div>
            @endif
            @if(session()->has('failed'))
            <div class="alert alert-danger" >
                {{ session()->get('failed') }}
            </div>
            @endif
        </div>
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Image</th>
                <th>Settings</th>
              </tr>
            </thead>
            <tbody>

                @foreach ($topics as $key => $topic)
                    <tr>
                        <td>{{$key}}</td>
                        <td>{{$topic->name}}</td>
                        <td>
                            <img src="{{ filter_var($topic->image, FILTER_VALIDATE_URL)?$topic->image:asset('uploads/'.$topic->image) }}" alt="" width="100" height="100">
                        </td>
                        <td>
                            <a href="{{route('topic.edit',$topic->id)}}">
                                <i class="far fa-edit nav-icon btn btn-primary"></i>
                            </a>
                            <a href="#" onclick="document.getElementById('formDelete').submit()">
                                <i class="far fa-trash-alt nav-icon btn btn-danger"></i>
                                <form id="formDelete" method="POST" action="{{route('topic.destroy',$topic->id)}}">
                                    @csrf
                                    @method('DELETE')
                                </form>
                            </a>


                        </td>
                    </tr>
                @endforeach


            </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
  </div>
@endsection