routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'admin'], function () {

    Route::get('/', function () {
        return view('admin.index');
    });

    Route::resource('/topic', 'control\TopicController');
    Route::resource('/post', 'control\PostController');

});

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Resources\Post\PostCollection;
use App\Model\Post;
use App\Model\Topic;
use Illuminate\Http\Request;

class PostController extends Controller
{





    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //

        // $post_total =  Post::orderBy('id','desc')->first()->id;

        $topic_id = $request->topic_id;
        $post_number = $request->post_number?$request->post_number:6;
        $page = $request->page?$request->page:0;


        // meta
        $total = $topic_id?count(Post::where('topic_id',$topic_id)->get()):count(Post::all());
        $current_page =$page>0?$page:1;
        $from  = $post_number * $page;
        $last_page = round($total/$post_number +1);
        $to =$post_number * $page + $post_number;

        //links
        $first = route('post.index',['page'=>$from,'topic_id'=>$topic_id,'post_number'=>$post_number]);
        $last = route('post.index',['page'=>$to,'topic_id'=>$topic_id,'post_number'=>$post_number]);
        $prev = route('post.index',['page'=>$current_page-1,'topic_id'=>$topic_id,'post_number'=>$post_number]);
        $next = route('post.index',['page'=>$current_page+1,'topic_id'=>$topic_id,'post_number'=>$post_number]);

        $pagination_arr = [
            'links'=>[
                'first'=>$first,
                'last'=>$last,
                'prev'=>$prev,
                'next'=>$next
            ],
            'meta'=>[
                'current'=>$current_page,
                'from'=>$from,
                'last_page'=>$last_page,
                'to'=>$to,
                'total'=>$total
            ]
        ];

        if($topic_id){

            return [
                'data'=>Post::where('topic_id',$topic_id)->take($post_number)->get(),
            ];

        }

        return [
            'data'=>Post::where('id','>',$total-($post_number*$current_page))->take($post_number)->get(),
            'pagination'=>$pagination_arr
        ];


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
        return $post;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        //
    }
}

app/Http/Controllers/control/PostController.php
<?php

namespace App\Http\Controllers\control;

use App\Http\Controllers\Controller;
use App\Model\Post;
use App\Model\Topic;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use PhpParser\Node\Stmt\Throw_;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $posts = Post::orderBy('id','desc')->paginate(20);
        return view('admin.post.index',['posts'=>$posts]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $topics = Topic::all();
        return view('admin.post.create',['topics'=>$topics]);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'name'=>'required',
            'topic'=>'required',
            'image'=>'mimes:png,jpg',
            'content'=>'required',
            'description'=>'required'
        ],[
            'name.require'=>"please enter name"
        ]);

        $fileName = 'default.jpg';
        if ($request->image) {
            try {
                $fileName = 'post-'.time().'.'.$request->image->extension();
                $request->image->move(public_path('uploads'), $fileName);
            } catch (\Throwable $th) {
                throw $th;
            }

        }





        $post = new Post();
        $post->topic_id = $request->topic;
        $post->title = $request->name;
        $post->slug = Str::slug($request->name,'-');
        $post->image = $fileName;
        $post->description = $request->description;
        $post->content = $request->content;
        $post->save();

        return redirect()->back()->with('success','Created successfully');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $post = Post::find($id)->first();
        $topics = Topic::all();
        return view('admin.post.edit',['post'=>$post,'topics'=>$topics]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $request->validate([
            'name'=>'required',
            'topic'=>'required',
            'image'=>'mimes:png,jpg',
            'content'=>'required',
            'description'=>'required'
        ],[
            'name.require'=>"please enter name"
        ]);

        $fileName = 'default.jpg';
        if ($request->image) {
            try {
                $fileName = 'post-'.time().'.'.$request->image->extension();
                $request->image->move(public_path('uploads'), $fileName);
            } catch (\Throwable $th) {
                throw $th;
            }

        }





        $post = Post::find($id)->first();
        $post->topic_id = $request->topic;
        $post->title = $request->name;
        $post->slug = Str::slug($request->name,'-');
        if($request->image){
            $post->image = $fileName;
        }
        $post->description = $request->description;
        $post->content = $request->content;
        $post->update();

        return redirect()->back()->with('success','Updated successfully');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
         //
         try {
            //code...
            Post::find($id)->delete();
        } catch (Throw_ $er) {
            return redirect()->back()->with('failed','Delete Failed');
        }

       return redirect()->back()->with('success','Delete Successfull');
    }
}

resources/views/admin/post/create.blade.php
@extends('admin.layouts.master')

@section('content')

    <div class="row">
        <div>
            @if(session()->has('success'))
            <div class="alert alert-success" >
                {{ session()->get('success') }}
            </div>
            @endif
            @if(session()->has('failed'))
            <div class="alert alert-success" >
                {{ session()->get('failed') }}
            </div>
            @endif
        </div>


        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                  <h3 class="card-title">Quick Example</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form role="form" action="{{route('post.store')}}" method="POST" enctype="multipart/form-data" >
                  @csrf
                    <div class="card-body">
                    <div class="form-group">
                      <label for="topicName">Title</label>
                      <input name="name" type="text" class="form-control" id="topicName" placeholder="Enter Topic Name">
                    </div>
                    <div class="form-group">
                        <label>Description</label>
                        <textarea name="description" class="form-control" rows="3" placeholder="Enter Description ..."></textarea>
                    </div>
                    <div class="form-group">
                        <label>Select Topic</label>
                        <select class="form-control" name="topic">

                            @foreach ($topics as $topic)
                                <option value="{{$topic->id}}">{{$topic->name}}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">
                      <label for="exampleInputFile">File input</label>
                      <div class="input-group">
                        <div class="custom-file">
                          <input name="image" type="file" class="custom-file-input" id="file">
                          <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                        </div>
                        <div class="input-group-append">
                          <span class="input-group-text" id="">Upload</span>
                        </div>
                      </div>
                    </div>
                    <div id="uploadForm">
                        {{-- file preview here --}}
                    </div>

                    <div class="form-group">
                        <h3>Content</h3>
                        <textarea name="content" class="textarea" id="" cols="30" rows="10"></textarea>
                    </div>
                  </div>
                  <!-- /.card-body -->

                  <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </div>
                </form>
              </div>
        </div>

    </div>
@endsection

resources/views/admin/post/edit.blade.php
@extends('admin.layouts.master')

@section('content')

    <div class="row">
        <div>
            @if(session()->has('success'))
            <div class="alert alert-success" >
                {{ session()->get('success') }}
            </div>
            @endif
            @if(session()->has('failed'))
            <div class="alert alert-success" >
                {{ session()->get('failed') }}
            </div>
            @endif
        </div>


        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                  <h3 class="card-title">Quick Example</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form role="form" action="{{route('post.update',$post->id)}}" method="POST" enctype="multipart/form-data" >
                  @csrf
                  @method('PUT')
                    <div class="card-body">
                    <div class="form-group">
                      <label for="topicName">Title</label>
                      <input value="{{$post->title}}" name="name" type="text" class="form-control" id="topicName" placeholder="Enter Topic Name">
                    </div>
                    <div class="form-group">
                        <label>Description</label>
                        <textarea name="description" class="form-control" rows="3" placeholder="Enter Description ...">
                            {{$post->description}}
                        </textarea>
                    </div>
                    <div class="form-group">
                        <label>Select Topic</label>
                        <select class="form-control" name="topic">
                            <option value="{{$post->topic->id}}">{{$post->topic->name}}</option>
                            @foreach ($topics as $topic)
                                <option value="{{$topic->id}}">{{$topic->name}}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group" id="uploadForm">
                      <label for="exampleInputFile">File input</label>
                      <div class="input-group">
                        <div class="custom-file">
                          <input name="image" type="file" class="custom-file-input" id="file">
                          <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                        </div>
                        <div class="input-group-append">
                          <span class="input-group-text" id="">Upload</span>
                        </div>
                      </div>
                    </div>
                    <img src="{{ filter_var($post->image, FILTER_VALIDATE_URL)?$post->image:asset('uploads/'.$post->image) }}" alt="" width="100" height="100">


                    <div class="form-group">
                        <h3>Content</h3>
                        <textarea name="content" class="textarea" id="" cols="30" rows="10">
                            {{$post->content}}
                        </textarea>
                    </div>
                  </div>
                  <!-- /.card-body -->

                  <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </div>
                </form>
              </div>
        </div>

    </div>
@endsection

resources/views/admin/post/index.blade.php
@extends('admin.layouts.master')

@section('content')
<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Responsive Hover Table</h3>

          <div class="card-tools">
            <a href="{{route('post.create')}}" class="btn btn-success" style="margin-left:100">Add New</a>

            <div class="input-group input-group-sm" style="width: 150px;">

              <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

              <div class="input-group-append">
                <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
              </div>
            </div>
          </div>
        </div>
        <div>
            @if(session()->has('success'))
            <div class="alert alert-success" >
                {{ session()->get('success') }}
            </div>
            @endif
            @if(session()->has('failed'))
            <div class="alert alert-danger" >
                {{ session()->get('failed') }}
            </div>
            @endif
        </div>
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Description</th>
                <th>Image</th>
                <th>Topic</th>
                <th>Settings</th>
              </tr>
            </thead>
            <tbody>

                @foreach ($posts as $key => $post)
                    <tr>
                        <td>{{$key}}</td>
                        <td>{{$post->title}}</td>
                        <td>{{$post->description}}</td>

                        <td>
                            <img src="{{ filter_var($post->image, FILTER_VALIDATE_URL)?$post->image:asset('uploads/'.$post->image) }}" alt="" width="100" height="100">
                        </td>
                        <td>
                            <a href="{{route('topic.index',$post->topic->id)}}">{{$post->topic->name}}</a>
                        </td>
                        <td>
                            <a href="{{route('post.edit',$post->id)}}">
                                <i class="far fa-edit nav-icon btn btn-primary"></i>
                            </a>
                            <a href="#" onclick="document.getElementById('formDelete').submit()">
                                <i class="far fa-trash-alt nav-icon btn btn-danger"></i>
                                <form id="formDelete" method="POST" action="{{route('post.destroy',$post->id)}}">
                                    @csrf
                                    @method('DELETE')
                                </form>
                            </a>


                        </td>
                    </tr>
                @endforeach


            </tbody>
          </table>
        </div>
        <div style="display:flex;justify-content:center">{{$posts->links()}}</div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
  </div>
@endsection